@url = http://127.0.0.1:8000
@token = 6|vftpkXeON6zcqiYHbaDEye4PGKPqif7qD9LLZv0973d4a515
### Health Check
get {{url}}/api/health
Accept: application/json
Content-Type: application/json

### Post User
post {{url}}/api/user
Accept: application/json
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com",
    "password": "123456"
}

### Get auth
post {{url}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "123456"
}

### Get User
get {{url}}/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Post Expense
post {{url}}/api/expenses
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "description": "Expense test request",
    "value": 150,
    "date": "2024-01-27",
    "type": "fly"
}

### get Expense
get {{url}}/api/expenses
Authorization: Bearer {{token}}
